#pragma once

enum CHANNEL_ID { CHANNEL_PLAYER, CHANNEL_MONSTER,  CHANNEL_SKILL, CHANNEL_GULP,
CHANNEL_ROLL, CHANNEL_HAMMER01, CHANNEL_HAMMER02, CHANNEL_GUN, CHANNEL_PLAYERGUN,
CHANNEL_GASPELLAHIT, CHANNEL_DEFENSEWING,    CHANNEL_DEFENSEGUN,      
CHANNEL_SUBTITLE00,  CHANNEL_SUBTITLE01,  CHANNEL_SUBTITLE02,  CHANNEL_SUBTITLE03,  CHANNEL_SUBTITLE04, CHANNEL_SUBTITLE05,
 CHANNEL_SUBTITLE06, CHANNEL_SUBTITLE07, CHANNEL_SUBTITLE08, CHANNEL_SUBTITLE09, CHANNEL_SUBTITLE10, CHANNEL_SUBTITLE11,
   CHANNEL_SUBTITLE12, CHANNEL_SUBTITLE13, CHANNEL_SUBTITLE14,  CHANNEL_SUBTITLE16, CHANNEL_SUBTITLE17,
    CHANNEL_SUBTITLE18, CHANNEL_SUBTITLE19, CHANNEL_SUBTITLE20, CHANNEL_SUBTITLE21, CHANNEL_SUBTITLE22,
    CHANNEL_SUBTITLE23, CHANNEL_SUBTITLE24, CHANNEL_SUBTITLE25, CHANNEL_SUBTITLE26, CHANNEL_SUBTITLE27,
	CHANNEL_SUBTITLE28, CHANNEL_SUBTITLE29,
	CHANNEL_OBJFALLING,

CHANNEL_EFFECT,  CHANNEL_BGM, CHANNEL_END };


// OBJECT
enum eObjectType
{
	OBJ_PORTAL, OBJ_TILE, OBJ_GROUND,   
	OBJ_MONSTER, OBJ_PLAYER_BULLET, OBJ_PLAYER, OBJ_MONSTER_BULLET, OBJ_STRUCTURE,
	OBJ_ITEM, OBJ_BOX,
	OBJ_EFFECT, OBJ_UI, OBJ_SCREEN, OBJ_BANDIBUL, OBJ_MOUSE,
	OBJ_END,
};

enum eObjectDir
{
	DIR_B, DIR_L, DIR_LB, DIR_LT,
	DIR_R, DIR_RB, DIR_RT, DIR_T,
	DIR_END
};

enum eOBJECT_RESULT
{
	OR_OK = 0, OR_DELETE, OR_EXIT,
};

// Y소팅 위한 Render ID
enum eRenderID
{
	RENDER_STRUCTURE_BACKWARD,
	RENDER_GROUND,
	RENDER_BACK,
	RENDER_STRUCTURE_FORWARD,
	RENDER_OBJ,
	RENDER_ITEM,
	RENDER_EFFECT, RENDER_UI, RENDER_SCREEN, RENDER_SUBTITLE, RENDER_END,
};

// PLAYER
enum ePlayerState
{
	PLAYER_IDLE, PLAYER_RUN, 
	PLAYER_HAMMER, PLAYER_ROLL, PLAYER_GUN,
	PLAYER_DEATH, PLAYER_DRINKING, PLAYER_DROP,
	PLAYER_LIE, PLAYER_STANDUP, PLAYER_WAKEUP,
};

// EFFECT
enum eBreakID
{
	BREAK_GASPELLA, BREAK_DEFENSE, BREAK_BOSS,
	BREAK_MYOBJECT,
};
//////////////////////////////////////////////////////////////////////////////////////////////////////

/// 옵저버

enum DATAID
{
	PLAYER_DATA,
	PLAYER_MATRIX,
	PLAYER_END
};
//////////////////////////////

enum eCollisionID
{
// 	COL_PLAYER_GASPELLA,
// 	COL_PLAYER_DEFENSE,
	COL_PLAYER_MONSTER,
	COL_PLAYER_MONBULLET,
	COL_PLAYER_BOSS,
	COL_PLAYER_ITEM,
	COL_PLAYER_PORTAL,
	COL_HAMMER_MONSTER,
	COL_HAMMER_MYOBJECT,
	COL_BULLET_MONSTER,
	COL_BULLET_MYOBJECT,
	COL_BULLET_PLAYER,
	
	COL_END,
};

enum eMonCollisionID
{
	MONCOL_BULLET,
	MONCOL_HAMMER,
	MONCOL_END,
};

enum eTextureType
{
	TEX_SINGLE, TEX_MULTI, TEX_END,
};

enum eSceneType
{
	SCENE_LOGO,
	SCENE_LOGO2,
	SCENE_MENU,
	SCENE_STAGE1,
	SCENE_DIA,
	SCENE_STAGE2,
	SCENE_STAGE3,
	SCENE_END,
};


enum eMessageID
{
	MESSAGE_PLAYER_DATA,
	MESSAGE_PLAYER_MATRIX,
	MESSAGE_END,
};

// 툴

enum eViewID
{
	VIEW_MAINVIEW, VIEW_MAPTOOL, VIEW_UNITTOOL,
	VIEW_OBJTOOL, VIEW_PATHFIND, VIEW_END
};